[package]
name = "ticketing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ticketing"

[features]
default = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
no-log-ix-name = []

[dependencies]
anchor-lang = { workspace = true }
